// Define the structure of the data we care about
export interface SongInfo {
    videoId: string;
    title: string;
    description: string;
}

/**
 * Fetches all items from a given YouTube Playlist ID.
 * Handles pagination automatically to bypass the 50-item limit.
 */
export async function fetchAllPlaylistItems(playlistId: string, apiKey: string): Promise<SongInfo[]> {
    const allSongs: SongInfo[] = [];
    let nextPageToken: string | undefined = undefined;
    
    // The base URL for the YouTube Data API v3 playlistItems endpoint
    const baseUrl = 'https://www.googleapis.com/youtube/v3/playlistItems';

    try {
        do {
            // Construct the URL with required parameters
            const url = new URL(baseUrl);
            url.searchParams.append('part', 'snippet');
            url.searchParams.append('playlistId', playlistId);
            url.searchParams.append('maxResults', '50');
            url.searchParams.append('key', apiKey);
            
            // Add the page token if we have one from a previous request
            if (nextPageToken) {
                url.searchParams.append('pageToken', nextPageToken);
            }

            // Make the API call
            const response = await fetch(url.toString());
            
            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(`YouTube API Error: ${errorData.error?.message || response.statusText}`);
            }

            const data = await response.json();

            // Extract the video details we need for Gemini to classify
            const items = data.items || [];
            for (const item of items) {
                // Ensure the item is actually a video (sometimes playlists have deleted/private videos)
                if (item.snippet && item.snippet.resourceId.videoId) {
                    allSongs.push({
                        videoId: item.snippet.resourceId.videoId,
                        title: item.snippet.title,
                        description: item.snippet.description
                    });
                }
            }

            // Grab the token for the next page, if it exists
            nextPageToken = data.nextPageToken;

        } while (nextPageToken); // Keep looping until there are no more pages

        return allSongs;

    } catch (error) {
        console.error("Failed to fetch playlist items:", error);
        throw error;
    }
}

export function extractPlaylistId(input: string): string {
    // 1. If it's a URL, try to grab the 'list' parameter
    if (input.includes('youtube.com') || input.includes('youtu.be')) {
        try {
            const url = new URL(input);
            const listId = url.searchParams.get('list');
            
            if (listId) return listId;
            
            throw new Error("Could not find a 'list=' parameter in that URL. Are you sure it's a playlist?");
        } catch (e: any) {
            throw new Error(e.message || "Invalid YouTube URL provided.");
        }
    }
    
    // 2. If they just pasted an ID, do a basic length check
    if (input.length < 10) {
        throw new Error("That Playlist ID looks too short to be valid.");
    }
    
    return input;
}
/**
 * Creates a new, private YouTube playlist.
 * Returns the ID of the newly created playlist.
 */
export async function createPlaylist(title: string, accessToken: string): Promise<string> {
    const url = 'https://www.googleapis.com/youtube/v3/playlists?part=snippet,status';
    
    const body = {
        snippet: {
            title: `Split: ${title}`,
            description: 'Auto-generated by Playlist Splitter'
        },
        status: {
            privacyStatus: 'private' // Keep it private by default!
        }
    };

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Failed to create playlist: ${errorData.error?.message}`);
    }

    const data = await response.json();
    return data.id; // The new playlist ID
}

/**
 * Adds a single video to a specified playlist.
 */
export async function addVideoToPlaylist(playlistId: string, videoId: string, accessToken: string): Promise<void> {
    const url = 'https://www.googleapis.com/youtube/v3/playlistItems?part=snippet';
    
    const body = {
        snippet: {
            playlistId: playlistId,
            resourceId: {
                kind: 'youtube#video',
                videoId: videoId
            }
        }
    };

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Failed to add video ${videoId}: ${errorData.error?.message}`);
    }
}